## name: Rainto's Config
## author: Rainto
## license: MIT

# Theme file
# $ kitty themes
# $ kitty list-fonts
include         ./theme.conf
font_family     JetBrainsMonoNL Nerd Font
blod_font       Serif Bold Italic
font_size       11
adjust_line_height  150%
adjust_column_width 0
cursor_trail    1
repaint_delay   0
# control
allow_remote_control yes
# listen_on unix:@kitty
listen_on unix:/tmp/kitty
shell_integration enabled
enable_audio_bell no

# 可选：提高图片质量
background_opacity 0.9
dynamic_background_opacity yes

# window
hide_window_decorations yes
window_padding_width 		10
background_opacity 			1
background_blur				5
remember_window_size 		yes

# keymap
map ctrl+shift+h no_op
map ctrl+shift+n no_op
map ctrl+shift+r no_op
map ctrl+shift+u no_op
