local icon = {
	ui = {
		Tag = "󰯏",
		Close = "",
		Bug = "",
		Pen = "",
		Left = "",
		Right = "",
		Separator = "",
		Search = "󰍉",
		Keyboard = "",
		Calendar = "",
		File = "󰈤",
		Indicator = "",
		Package = "󱧘",
		Layout = "",
		ArrowClosed = "",
		ArrowOpen = "",
		Folder = "",
		FolderOpen = "",
		Event = "",
	},
	package={
		Installed = "✓",
		Pending = "➜",
		Uninstalled = "✗",
	},
	diag = {
		-- Error = "",
		-- Warning = "",
		-- Information = "",
		-- Question = "",
		-- Hint = "󰌵",
		-- Hollow version
		Error = "󰅚",
		Warning = "󰀪",
		Information = "",
		Question = "",
		Hint = "󰌶",
	},
	type = {
		Array = "󰅪",
		Boolean = "",
		Null = "󰟢",
		Number = "",
		Object = "󰅩",
		String = "󰉿",
	},
	git = {
		Add = "",
		Branch = "",
		Diff = "",
		Git = "󰊢",
		Ignore = "",
		Mod = "M",
		Mod_alt = "",
		Remove = "-",
		Rename = "",
		Repo = "",
		Unmerged = "󰘬",
		Untracked = "󰞋",
		Unstaged = "",
		Staged = "",
		Conflict = "",
	},
	kind = {
		Break = "󰙧",
		Call = "󰃷",
		Case = "󰬶",
		Class = "󰠱",
		Color = "󰏘",
		Constant = "󰏿",
		Constructor = "",
		Continue = "󰞘",
		Declaration = "󰙠",
		Delete = "󱟁",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "󰇽",
		File = "󰈙",
		Folder = "󰉋",
		Fragment = "",
		Function = "󰊕",
		Implementation = "",
		Interface = "",
		Keyword = "󰌋",
		List = "󰅪",
		Loop = "󰑖",
		Method = "󰆧",
		Module = "",
		Namespace = "󰌗",
		Operator = "󰆕",
		Package = "",
		Property = "󰜢",
		Reference = "",
		Regex = "",
		Snippet = "",
		Statement = "󰅩",
		Struct = "",
		Switch = "",
		Text = "",
		TypeParameter = "󰅲",
		Undefined = "",
		Unit = "",
		Value = "󰎠",
		Variable = "",
		-- ccls-specific icons
		Macro = "",
		Parameter = "",
		StaticMethod = "",
		Terminal = "",
		TypeAlias = "",
	},
}

return icon
